### ISSUE TITLE
Error when running `php artisan dynamic-forms:install`

### ISSUE THREAD

**Issue by bilogic** [NIT-Administrative-Systems/dynamic-forms#356]
**Describe the bug**
```BASH
[/project]# php artisan dynamic-forms:install
Publishing file upload controller...

   ERROR  Command "dynamic-forms:installStorageController" is not defined. Did you mean one of these?

  ⇂ dynamic-forms:install

[/project]#
```

**To Reproduce**
1. Install Laravel Framework 9.26.1
2. `composer require northwestern-sysdev/dynamic-forms`
3. `php artisan dynamic-forms:install`

**Expected behavior**
Not expecting an error

**Have you customized the resources/js/formio/defaults.js` file?
- [x] No
- [ ] Yes (describe changes)

**Comment by EllisonTravel** [comment]
Hi there, I am receiving same error. Is there any workaround? Thank you

**Comment by bilogic** [comment]
Have a look at my PR, however, even with it, I ran into other difficulties.

If you are just looking to test out what form.io feels like, have a look here https://formio.github.io/formio.js/app/builder

**Comment by EllisonTravel** [comment]
Thanks a lot for getting back.
I had a look already on the demo. I was trying to advance to next step, try to install locally and see if/how it could work in our application.
I need to find a solution for forms.
Thanks again for getting back and working on this project 
I'm also looking into this project in parallel: https://github.com/kevinchappell/formBuilder 
not really sure the difference... 
Thanks 
Paulo

**Comment by bilogic** [comment]
Not to put this project down or anything (as it introduced me to form.io which is amazing!), but I ended up rolling my own package. 

I had a very quick glance at https://github.com/kevinchappell/formBuilder, it doesn't seem as full featured as form.io
Also, not sure if you are aware, but form.io is by another author, what this package does is to integrate it into Laravel.

What I meant to say is that, form.io is quite a complete solution, i.e. better :)

This page gives a pretty complete overview of how things work https://formio.github.io/formio.js/app/builder
The examples are also a good place to understand the capabilities https://formio.github.io/formio.js/app/examples/

**Comment by EllisonTravel** [comment]
Thanks for the feedback. I totally agree, they are very different and of course I would rather deal with something pluggable to Laravel than trying to plug-in my "own" solution. 
However, I do need to make a decision and find/test a solution soon. And if this works it will be amazing. If you will have a pro/support line with reasonable price, great, but at the moment, I can't install/test this, so I'm working on a plan B :)

**Comment by bilogic** [comment]
@EllisonTravel 

Could you provide a description of what you need?

**Comment by EllisonTravel** [comment]
What we need is pretty basic. A form that can be designed by the end-user and sent to external clients to fill-up. Information (and form structure in case it gets changed) should be saved in a database in JSON format. 
So, this package seems to do this and more however it can't be installed now due to the error above.  This is the reason I was trying FormBuilder as a backup.  
Will the issue with the installation be fixed someone soon and/or is there a workaround for this issue that would still allow me to install this package in a Laravel 9 app Livewire.   Thank you very much

**Comment by EllisonTravel** [comment]
Hi @bilogic , sorry for bugging you again. 
any luck with this issue and/or workaround to be able to install this package locally and test/see how it works?
thanks a lot 
Paulo

**Comment by bilogic** [comment]
> Not to put this project down or anything (as it introduced me to form.io which is amazing!), but I ended up rolling my own package.

@EllisonTravel I stopped working on this, my own package saves the designed forms in JSON format to database.

> If you will have a pro/support line with reasonable price

If you are still interested in my package, send me an email at lukuse@mailo.icu thanks

**Comment by GxSupport** [comment]
hello, first install 8.4.0 then update to 9.01

**Comment by EllisonTravel** [comment]
thank you. I tried that but other dependencies used by other projects seem to be blocking this installation. Is there any way this package installation could be fixed? or would you have any other suggestion? 
thanks
composer require northwestern-sysdev/dynamic-forms --with-all-dependencies
Using version ^0.9.1 for northwestern-sysdev/dynamic-forms
./composer.json has been updated
Running composer update northwestern-sysdev/dynamic-forms --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires northwestern-sysdev/dynamic-forms ^0.9.1 -> satisfiable by northwestern-sysdev/dynamic-forms[v0.9.1].
    - laravel/framework[v8.75.0, ..., 8.x-dev] require symfony/finder ^5.4 -> satisfiable by symfony/finder[v5.4.0-BETA1, ..., 5.4.x-dev].
    - Conclusion: don't install symfony/finder v5.4.11 (conflict analysis result)
    - Root composer.json requires laravel/framework ^8.75 -> satisfiable by laravel/framework[v8.75.0, ..., 8.x-dev].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require northwestern-sysdev/dynamic-forms:*" to figure out if any version is installable, or "composer require northwestern-sysdev/dynamic-forms:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
