### ISSUE TITLE
UserOnboarding and Documentation

### ISSUE THREAD

**Issue by infinite-dev22** [NIT-Administrative-Systems/dynamic-forms#375]
This is a good library but also complex to get started with because the documentation for this is so precise and not well explained

**Comment by HanustaviraGA** [comment]
@infinite-dev22 could you help me to point out what needs to be done from the beginning ?

**Comment by infinite-dev22** [comment]
Am not sure where to start from. Adding a well explained documentation on how this work and can be used(All use cases well shown off by example) could be of so much help to a person wanting to use or using this tool.

**Comment by HanustaviraGA** [comment]
![image](https://github.com/NIT-Administrative-Systems/dynamic-forms/assets/68433367/ef0a2b6a-01c4-4e99-86da-da521d62eda3)

Because as you can see, it called FormDefinition method on example, but never mention what has to be included above.

**Comment by infinite-dev22** [comment]
Sometime back I tried using this framework on my project but failed due to lack of proper documentation. That was last year, as of now there is a better documentation on how this can be used unlike back then. I think this issue was solved long before.
