### ISSUE TITLE
There is No clear way to use it via Laravel and error with controllers naming compared to web.php routes

### ISSUE THREAD

**Issue by mohammed-brain** [NIT-Administrative-Systems/dynamic-forms#426]
**There is No clear way to use it via Laravel and error with controllers naming compared to web.php routes**
There is No clear way to use it via Laravel and error with controllers naming compared to web.php routes

**go to web.php and to DynamicFormsResourceController.php**

**Expected behavior**

**Have you customized the resources/js/formio/defaults.js` file?
- [ ] No
- [ ] Yes (describe changes)

**Additional context**

**Comment by nie7321** [comment]
Thanks for reporting this! 

We've made some improvements to the docs and setup process in v1.0.0, including correcting the classes in the route stubs. I hope that helps!
